### __BUSA3020 Group Assignment - Predicting Airbnb Listing Prices in Sydney__

--- 

**Due Date:** Friday, 3 June 2022 @ 11.59pm (Week 13)

**Overview:**   

- In the group assignment you will form a team of up to 3 students (minimum 2) and participate in a forecasting competition on Kaggle
- The goal is to predict listed property prices of Airbnb stays based on various Airbnb characteristics and regression models

- You will:  
    - Write a problem statement and perform Exploratory Data Analysis  
    - Clean up data, deal with categorical features and missing observations, and create new variables (feature engineering)  
    - Construct and tune forecasting models, produce forecasts and submit your predictions to Kaggle  
    - Each member of the team will record a video presentation of their work  
    - Marks will be awarded producing a prediction in the top 3 positions of their unit as well as for reaching the highest ranking on Kaggle amongst all teams.

**Instructions:** 

- Form a team of 3 students (minimum 2 students)  
- Each team member needs to join [https://www.kaggle.com](https://www.kaggle.com/)  
- Choose a team leader and form a team in the competition [https://www.kaggle.com/t/caad5fd1f5134d86a15ab13d37d98d19](https://www.kaggle.com/t/caad5fd1f5134d86a15ab13d37d98d19)
    - Team leader to click on `team` and join and invite other team members to join
    - There are two MQBS BUSA units competing in this competition
    - Your **team's name must start** with your unit code, for instance you could have a team called BUSA3020_PR3D1CT0RS
- All team members should work on all the tasks listed below however   
    - **Choose a team member who will be responsible for one of each of the 3 tasks listed below**

**Marks**: 

- Total Marks: 40
- Your mark will consist of:  
    - 50% x overall assignment mark + 45% x mark for the task that you are responsible for + 5% x mark received from your teammates for your effort in group work 
- 7 marks will be deducted from each Task for which there is no video presentation

**Competition Marks:**
- 5 marks: Ranking in the top 3 places of your unit on Kaggle (make sure you name your team as instructed above)
- 2 marks: Reaching the first place in your unit  (make sure you name your team as instructed above)


**Submissions:**  

1. On Kaggle: submit your team's forecast in order to be ranked by Kaggle
    - Can do this as many times as necessary while building their model  
2. On iLearn **only team leader to submit** this Jupyter notebook re-named `Group_Assignment_MQ_ID.ipynb` where MQ_ID is team leader's MQ ID number 
    - The Jupyter notebook must contain team members names/ID numbers, and team name in the competition
    - Provide answers to the 3 Tasks below in the allocated cells including all codes/outputs/writeups 
    - One 15 minute video recording of your work 
        - Each team member to provide a 5 minute presentation of the Task that they led (it is best to jointly record your video using Zoom)
        - When recording your video make sure your face is visible, that you share your Jupyter Notebook and explain everything you've done in the submitted Jupyter notebook on screen
        - 7 marks will be deducted from each Task for which there is no video presentation or if you don't follow the above instructions
        
3. On iLearn each student needs to submit a file with their teammates' names, SID and a mark for their group effort (out of 100%)

---

**Fill out the following information**

For each team member provide name, Student ID number and which task is performed below

- Team Name on Kaggle: BUSA3020_TaoLaNhat
- Team Leader and Team Member 1: `Anh Dung Tu`
- Team Member 2: `Minh Chau Nguyen`
- Team Member 3: `Khanh Linh Pham`

In [1]:
import pandas as pd 
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

---

## Task 1: Problem Description and Initial Data Analysis

1. Read the Competition Overview on Kaggle [https://www.kaggle.com/t/caad5fd1f5134d86a15ab13d37d98d19](https://www.kaggle.com/t/caad5fd1f5134d86a15ab13d37d98d19)
2. Referring to Competition Overview and the data provided on Kaggle write about a 500 words **Problem Description** focusing on key points that will need to be addressed as first steps in Tasks 2 and 3 below, using the following headings:
    - Forecasting Problem
    - Evaluation Criteria
    - Types of Variables/Features
    - Data summary and main data characteristics
    - Missing Values (only explain what you found at this stage)
    
Total Marks: 11

In [2]:
#Task 1 code here, insert more cells if required
df_train = pd.read_csv("data/train.csv")
# df_train.info()

In [3]:
df_test = pd.read_csv("data/test.csv")
#df_test.info()

In [4]:
df = pd.concat([df_train, df_test], ignore_index = True)
#df.info()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 61 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   ID                                            10000 non-null  int64
 1   name                                          9998 non-null   object
 2   description                                   9846 non-null   object
 3   neighborhood_overview                         6943 non-null   object
 4   host_name                                     10000 non-null  object
 5   host_since                                    10000 non-null  object
 6   host_location                                 9996 non-null   object
 7   host_about                                    6110 non-null   object
 8   host_response_time                            6821 non-null   object
 9   host_response_rate                            6821 non-null   object
 10  host_acceptance_rate                          6970 non-null   object
 11  host_is_superhost                             10000 non-null  object
 12  host_neighbourhood                            5825 non-null   object
 13  host_listings_count                           10000 non-null  float64
 14  host_verifications                            10000 non-null  object
 15  host_has_profile_pic                          10000 non-null  object
 16  host_identity_verified                        10000 non-null  object
 17  neighbourhood                                 6944 non-null   object
 18  neighbourhood_cleansed                        9850 non-null   object
 19  latitude                                      10000 non-null  float64
 20  longitude                                     10000 non-null  float64
 21  property_type                                 9877 non-null   object
 22  room_type                                     9825 non-null   object
 23  accommodates                                  10000 non-null  int64
 24  bathrooms                                     9990 non-null   object
 25  bedrooms                                      9162 non-null   float64
 26  beds                                          9631 non-null   float64
 27  amenities                                     10000 non-null  object
 28  minimum_nights                                10000 non-null  int64
 29  maximum_nights                                10000 non-null  int64
 30  minimum_minimum_nights                        9945 non-null   float64
 31  maximum_minimum_nights                        10000 non-null  float64
 32  minimum_maximum_nights                        10000 non-null  float64
 33  maximum_maximum_nights                        9945 non-null   float64
 34  minimum_nights_avg_ntm                        10000 non-null  float64
 35  maximum_nights_avg_ntm                        10000 non-null  float64
 36  has_availability                              10000 non-null  object
 37  availability_30                               10000 non-null  int64
 38  availability_60                               10000 non-null  int64
 39  availability_90                               10000 non-null  int64
 40  availability_365                              9933 non-null   float64
 41  number_of_reviews                             10000 non-null  int64
 42  number_of_reviews_ltm                         10000 non-null  int64
 43  number_of_reviews_l30d                        10000 non-null  int64
 44  first_review                                  9420 non-null   object
 45  last_review                                   9420 non-null   object
 46  review_scores_rating                          9420 non-null   float64
 47  review_scores_accuracy                        9149 non-null   float64
 48  review_scores_cleanliness                     9155 non-null   float64
 49  review_scores_checkin                         9148 non-null   float64
 50  review_scores_communication                   9156 non-null   float64
 51  review_scores_location                        9148 non-null   float64
 52  review_scores_value                           9146 non-null   float64
 53  license                                       5739 non-null   object
 54  instant_bookable                              10000 non-null  object
 55  calculated_host_listings_count                10000 non-null  int64
 56  calculated_host_listings_count_entire_homes   10000 non-null  int64
 57  calculated_host_listings_count_private_rooms  10000 non-null  int64
 58  calculated_host_listings_count_shared_rooms   10000 non-null  int64
 59  reviews_per_month                             9420 non-null   float64
 60  price                                         7000 non-null   object
dtypes: float64(20), int64(14), object(27)
memory usage: 4.7+ MB

In [6]:
df.describe()

,ID,host_listings_count,latitude,longitude,accommodates,bedrooms,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,9162.000000,9631.000000,10000.000000,10000.000000,9945.000000,10000.000000,10000.000000,9.945000e+03,10000.000000,1.000000e+04,10000.000000,10000.000000,10000.000000,9933.000000,10000.000000,10000.000000,10000.000000,9420.000000,9149.000000,9155.000000,9148.000000,9156.000000,9148.000000,9146.000000,10000.000000,10000.000000,10000.000000,10000.000000,9420.000000
mean,4999.50000,12.871200,-33.853093,151.194656,3.62980,1.777450,2.171633,43.501700,828.822200,42.506083,43.991300,907.023700,2.376217e+06,43.257400,2.169292e+06,8.106200,20.726000,35.394000,137.551898,28.467700,5.147600,0.547500,4.544779,4.742338,4.623815,4.835223,4.832469,4.831458,4.635984,9.916300,8.151700,1.647800,0.054400,0.797516
std,2886.89568,38.223115,0.087999,0.100407,2.28063,1.070244,1.649610,48.756685,451.594808,48.739458,48.155792,408.469203,7.138470e+07,48.461728,6.548772e+07,10.373673,21.920519,33.900282,137.756841,52.898448,11.161706,1.387637,0.914349,0.489796,0.579326,0.402332,0.418854,0.349528,0.505872,25.341076,23.494082,9.719661,0.638656,1.151838
min,0.00000,0.000000,-34.100680,150.630490,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2499.75000,1.000000,-33.895832,151.167258,2.00000,1.000000,1.000000,2.000000,365.000000,2.000000,3.000000,1125.000000,1.125000e+03,2.000000,1.125000e+03,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,4.530000,4.700000,4.500000,4.840000,4.840000,4.800000,4.522500,1.000000,1.000000,0.000000,0.000000,0.080000
50%,4999.50000,2.000000,-33.877735,151.212825,3.00000,1.000000,2.000000,7.000000,1125.000000,7.000000,10.000000,1125.000000,1.125000e+03,7.000000,1.125000e+03,2.000000,13.000000,31.000000,88.000000,7.000000,0.000000,0.000000,4.820000,4.900000,4.810000,4.980000,4.990000,4.950000,4.760000,1.000000,1.000000,0.000000,0.000000,0.330000
75%,7499.25000,5.000000,-33.814463,151.261212,4.00000,2.000000,3.000000,90.000000,1125.000000,90.000000,90.000000,1125.000000,1.125000e+03,90.000000,1.125000e+03,14.000000,39.000000,67.000000,286.000000,30.000000,6.000000,0.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,4.980000,4.000000,2.000000,1.000000,0.000000,1.060000
max,9999.00000,457.000000,-33.392670,151.340410,16.00000,18.000000,39.000000,1125.000000,1162.000000,1125.000000,1125.000000,1162.000000,2.147484e+09,1125.000000,2.142625e+09,30.000000,60.000000,90.000000,365.000000,756.000000,280.000000,30.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,197.000000,197.000000,100.000000,17.000000,24.270000

---

## Task 2: Data Cleaning, Missing Observations and Feature Engineering
- In this task you will follow a set of instructions/questions listed below.
- Make sure you **explain** each step you do both in Markdown text and on your video.
    - Do not just read out your commands without exaplaining what they do and why you used them 

Total Marks: 11

**Task 2, Question 1**: Clean **all** numerical features and the target variable `price` so that they can be used in training algorithms. For instance, `host_response_rate` feature is in object format containing both numerical values and text. Extract numerical values (or equivalently eliminate the text) so that the numerical values can be used as a regular feature.  
(2 marks)

In [7]:
## Task 2, Question 1 Code Here
df['host_response_rate']= ((df['host_response_rate'].str.replace("%","")).astype(float))/100
df['host_acceptance_rate']= ((df['host_acceptance_rate'].str.replace("%","")).astype(float))/100
df['price'] = ((df['price'].str.replace("$","")).str.replace(",","")).astype(float)

<ipython-input-7-3a05a1d588e0>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['price'] = ((df['price'].str.replace("$","")).str.replace(",","")).astype(float)

`(Task 2, Question 1 Text Here - insert more cells as required)`

**Task 2, Question 2** Create at least 4 new features from existing features which contain multiple items of information, e.g. creating `email`,  `phone`, `reviews`, `jumio`, etc. from feature `host_verifications`.  
(2 marks)

In [8]:
## Task 2, Question 2 Code Here
## Determine 5 most-used verification types
for i in ['email', 'phone', 'manual_online', 'facebook', 'reviews', 'manual_offline', 'jumio', 'offline_government_id', 'selfie', 'government_id', 'identity_manual', 'work_email']:
    c = 0
    for index, row in df.iterrows():
        if i in (row["host_verifications"]):
            c +=1
    print('Count of verification type', i, c)

Count of verification type email 9232
Count of verification type phone 9976
Count of verification type manual_online 203
Count of verification type facebook 1428
Count of verification type reviews 6350
Count of verification type manual_offline 213
Count of verification type jumio 6697
Count of verification type offline_government_id 5297
Count of verification type selfie 3262
Count of verification type government_id 7241
Count of verification type identity_manual 3071
Count of verification type work_email 1828

In [9]:
def email_verify(df):
    for i in range(len(df)):
        if 'email' in df['host_verifications']:
            return 1 
        else:
            return 0
def phone_verify(df):
    for i in range(len(df)):
        if 'phone' in df['host_verifications']:
            return 1 
        else:
            return 0
def governmentid_verify(df):
    for i in range(len(df)):
        if 'government_id' in df['host_verifications']:
            return 1 
        else:
            return 0
def jumio_verify(df):
    for i in range(len(df)):
        if 'jumio' in df['host_verifications']:
            return 1 
        else:
            return 0
def reviews_verify(df):
    for i in range(len(df)):
        if 'reviews' in df['host_verifications']:
            return 1 
        else:
            return 0
df['host_email']= df.apply(email_verify, axis = 1)
df['host_phone']= df.apply(phone_verify, axis = 1)
df['host_governmentId']= df.apply(governmentid_verify, axis = 1)
df['host_jumio']= df.apply(jumio_verify, axis = 1)
df['host_reviews']= df.apply(reviews_verify, axis = 1)

In [10]:
max(df['amenities'], key = len)

'["Clothing storage: wardrobe, walk-in closet, and dresser", "Hot water", "Coffee maker", "Free dryer \\u2013 In building", "Toaster", "Heating", "Long term stays allowed", "Extra pillows and blankets", "Dining table", "Private fenced garden or backyard", "Bikes", "Hair dryer", "Conditioner", "Drying rack for clothing", "Babysitter recommendations", "Laundromat nearby", "Fire pit", "Bathtub", "Oven", "Private entrance", "Lockbox", "Beach essentials", "Dedicated workspace: monitor, desk, table, and office chair", "Bread maker", "Ceiling fan", "Microwave", "Iron", "Free washer \\u2013 In building", "68\\" HDTV with Amazon Prime Video, Apple TV, Netflix, standard cable", "Refrigerator", "Outdoor shower", "Board games", "Fire extinguisher", "Hot water kettle", "Piano", "Samsung Bar Bluetooth sound system", "Children\\u2019s dinnerware", "Stove", "Portable fans", "Ethernet connection", "Bed linens", "Game console", "Cable TV", "Hangers", "Pack \\u2019n play/Travel crib", "BBQ grill", "Body soap", "First aid kit", "Smoke alarm", "Room-darkening shades", "Luggage dropoff allowed", "Private patio or balcony", "Essentials", "Cooking basics", "Barbecue utensils", "Baking sheet", "Outdoor furniture", "Outdoor dining area", "Private outdoor saltwater pool", "Wifi", "Free street parking", "Dishwasher", "Freezer", "Nespresso machine", "Dishes and silverware", "Wine glasses", "Cleaning products", "Free parking on premises", "Shampoo", "Shower gel", "Children\\u2019s books and toys", "Kitchen", "Baby safety gates", "High chair", "Rice maker", "Trash compactor", "Mosquito net"]'

In [11]:
for i in ["Clothing storage: wardrobe, walk-in closet, and dresser", "Hot water", "Coffee maker", "Free dryer \\u2013 In building", "Toaster", "Heating", "Long term stays allowed", "Extra pillows and blankets", "Dining table", "Private fenced garden or backyard", "Bikes", "Hair dryer", "Conditioner", "Drying rack for clothing", "Babysitter recommendations", "Laundromat nearby", "Fire pit", "Bathtub", "Oven", "Private entrance", "Lockbox", "Beach essentials", "Dedicated workspace: monitor, desk, table, and office chair", "Bread maker", "Ceiling fan", "Microwave", "Iron", "Free washer \\u2013 In building", "68\\ HDTV with Amazon Prime Video, Apple TV, Netflix, standard cable", "Refrigerator", "Outdoor shower", "Board games", "Fire extinguisher", "Hot water kettle", "Piano", "Samsung Bar Bluetooth sound system", "Children\\u2019s dinnerware", "Stove", "Portable fans", "Ethernet connection", "Bed linens", "Game console", "Cable TV", "Hangers", "Pack \\u2019n play/Travel crib", "BBQ grill", "Body soap", "First aid kit", "Smoke alarm", "Room-darkening shades", "Luggage dropoff allowed", "Private patio or balcony", "Essentials", "Cooking basics", "Barbecue utensils", "Baking sheet", "Outdoor furniture", "Outdoor dining area", "Private outdoor saltwater pool", "Wifi", "Free street parking", "Dishwasher", "Freezer", "Nespresso machine", "Dishes and silverware", "Wine glasses", "Cleaning products", "Free parking on premises", "Shampoo", "Shower gel", "Children\\u2019s books and toys", "Kitchen", "Baby safety gates", "High chair", "Rice maker", "Trash compactor", "Mosquito net"]:
    c=0
    for index, row in df.iterrows():
        if i in (row["amenities"]):
            c +=1
    print('Count of amenities type', i, c)

Count of amenities type Clothing storage: wardrobe, walk-in closet, and dresser 3
Count of amenities type Hot water 7143
Count of amenities type Coffee maker 3322
Count of amenities type Free dryer \u2013 In building 56
Count of amenities type Toaster 1401
Count of amenities type Heating 6790
Count of amenities type Long term stays allowed 9301
Count of amenities type Extra pillows and blankets 3623
Count of amenities type Dining table 1333
Count of amenities type Private fenced garden or backyard 402
Count of amenities type Bikes 52
Count of amenities type Hair dryer 7624
Count of amenities type Conditioner 1153
Count of amenities type Drying rack for clothing 993
Count of amenities type Babysitter recommendations 326
Count of amenities type Laundromat nearby 685
Count of amenities type Fire pit 173
Count of amenities type Bathtub 1618
Count of amenities type Oven 4655
Count of amenities type Private entrance 3707
Count of amenities type Lockbox 2639
Count of amenities type Beach essentials 681
Count of amenities type Dedicated workspace: monitor, desk, table, and office chair 1
Count of amenities type Bread maker 104
Count of amenities type Ceiling fan 610
Count of amenities type Microwave 5763
Count of amenities type Iron 8168
Count of amenities type Free washer \u2013 In building 81
Count of amenities type 68\ HDTV with Amazon Prime Video, Apple TV, Netflix, standard cable 0
Count of amenities type Refrigerator 5866
Count of amenities type Outdoor shower 158
Count of amenities type Board games 344
Count of amenities type Fire extinguisher 3830
Count of amenities type Hot water kettle 1590
Count of amenities type Piano 83
Count of amenities type Samsung Bar Bluetooth sound system 1
Count of amenities type Children\u2019s dinnerware 565
Count of amenities type Stove 4893
Count of amenities type Portable fans 766
Count of amenities type Ethernet connection 866
Count of amenities type Bed linens 5155
Count of amenities type Game console 211
Count of amenities type Cable TV 1548
Count of amenities type Hangers 8390
Count of amenities type Pack \u2019n play/Travel crib 808
Count of amenities type BBQ grill 1895
Count of amenities type Body soap 1261
Count of amenities type First aid kit 3586
Count of amenities type Smoke alarm 9198
Count of amenities type Room-darkening shades 1471
Count of amenities type Luggage dropoff allowed 2413
Count of amenities type Private patio or balcony 1182
Count of amenities type Essentials 9293
Count of amenities type Cooking basics 5735
Count of amenities type Barbecue utensils 791
Count of amenities type Baking sheet 676
Count of amenities type Outdoor furniture 1203
Count of amenities type Outdoor dining area 869
Count of amenities type Private outdoor saltwater pool 5
Count of amenities type Wifi 9351
Count of amenities type Free street parking 4233
Count of amenities type Dishwasher 3806
Count of amenities type Freezer 1386
Count of amenities type Nespresso machine 423
Count of amenities type Dishes and silverware 6227
Count of amenities type Wine glasses 1387
Count of amenities type Cleaning products 1298
Count of amenities type Free parking on premises 4442
Count of amenities type Shampoo 7300
Count of amenities type Shower gel 2061
Count of amenities type Children\u2019s books and toys 964
Count of amenities type Kitchen 9170
Count of amenities type Baby safety gates 234
Count of amenities type High chair 1024
Count of amenities type Rice maker 382
Count of amenities type Trash compactor 45
Count of amenities type Mosquito net 96

In [12]:
def kitchen(df):
    for i in range(len(df)):
        if 'Kitchen' in df['amenities']:
            return 1 
        else:
            return 0
def essential(df):
    for i in range(len(df)):
        if 'Essentials' in df['amenities']:
            return 1 
        else:
            return 0
def smokealarm(df):
    for i in range(len(df)):
        if 'Smoke alarm' in df['amenities']:
            return 1 
        else:
            return 0
def longterm(df):
    for i in range(len(df)):
        if 'Long term stays allowed' in df['amenities']:
            return 1 
        else:
            return 0
def wifi(df):
    for i in range(len(df)):
        if 'Wifi' in df['amenities']:
            return 1 
        else:
            return 0
df['kitchen']= df.apply(kitchen, axis = 1)
df['wifi']= df.apply(wifi, axis = 1)
df['smoke_alarm']= df.apply(smokealarm, axis = 1)
df['longterm_stay']= df.apply(longterm, axis = 1)
df['essentials']= df.apply(essential, axis = 1)

`(Task 2, Question 2 Text Here - insert more cells as required)`

**Task 2, Question 3**: Impute missing values for all features in both training and test datasets.   
(2 marks)

In [13]:
df.isnull().sum()

ID                                                 0
name                                               2
description                                      154
neighborhood_overview                           3057
host_name                                          0
host_since                                         0
host_location                                      4
host_about                                      3890
host_response_time                              3179
host_response_rate                              3179
host_acceptance_rate                            3030
host_is_superhost                                  0
host_neighbourhood                              4175
host_listings_count                                0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood                                   3056
neighbourhood_cleansed                           150
latitude                                           0
longitude                                          0
property_type                                    123
room_type                                        175
accommodates                                       0
bathrooms                                         10
bedrooms                                         838
beds                                             369
amenities                                          0
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                            55
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                            55
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                  67
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                     580
last_review                                      580
review_scores_rating                             580
review_scores_accuracy                           851
review_scores_cleanliness                        845
review_scores_checkin                            852
review_scores_communication                      844
review_scores_location                           852
review_scores_value                              854
license                                         4261
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                580
price                                           3000
host_email                                         0
host_phone                                         0
host_governmentId                                  0
host_jumio                                         0
host_reviews                                       0
kitchen                                            0
wifi                                               0
smoke_alarm                                        0
longterm_stay                                      0
essentials                                         0
dtype: int64

In [14]:
# Task 2, Question 3 Code Here
## Impute text/categorical variables with "Unknown"
df[['name','description','neighborhood_overview', 'host_about','host_neighbourhood', 'neighbourhood', 'license']]=df[['name','description','neighborhood_overview', 'host_about','host_neighbourhood', 'neighbourhood','license']].fillna(value = 'Unknown')
df['host_location']= df['host_location'].fillna(value = 'Australia')

## Impute categorical variables with the most frequent value
mode_values = {"host_response_time": df["host_response_time"].mode()[0],"property_type": df["property_type"].mode()[0], "room_type": df["room_type"].mode()[0],"bathrooms": df["bathrooms"].mode()[0] }
df.fillna(value = mode_values, inplace = True)

# Impute numerical variables
## Using min and max values:
df['minimum_minimum_nights'].fillna(value = df['minimum_minimum_nights'].min(), inplace = True)
df['maximum_maximum_nights'].fillna(value = df['maximum_maximum_nights'].max(), inplace = True)
## Using mean values:
mean_values = {'availability_365': df['availability_365'].mean(),'host_response_rate': df['host_response_rate'].mean(),'host_acceptance_rate': df['host_acceptance_rate'].mean(),"bedrooms":df['bedrooms'].mean(), "beds":df["beds"].mean(),'review_scores_rating':df['review_scores_rating'].mean(), 'review_scores_accuracy':df['review_scores_accuracy'].mean(),'review_scores_cleanliness':df['review_scores_cleanliness'].mean(),'review_scores_checkin':df['review_scores_checkin'].mean(),'review_scores_communication':df['review_scores_communication'].mean(),'review_scores_location':df['review_scores_location'].mean(),'review_scores_value':df['review_scores_value'].mean(),'reviews_per_month':df['reviews_per_month'].mean()}
df.fillna(value = mean_values, inplace = True)

# Impute datetime variables
## Convert type from object to datetime 
df['first_review']= pd.to_datetime(df['first_review'])
df['last_review']= pd.to_datetime(df['last_review'])
## Fill NaN values of the datetime:
df['first_review'].fillna(value = min(df['first_review']), inplace = True)
df['last_review'].fillna(value = max(df['last_review']), inplace = True)

`(Task 2, Question 3 Text Here - insert more cells as required)`

**Task 2, Question 4**: Encode all categorical variables appropriately as discussed in class. 


Where a categorical feature contains more than 5 unique values, map the features into 5 most frequent values + 'other' and then encode appropriately. For instance, you could group then map `property_type` into 5 basic types + 'other': [entire rental unit, private room, entire room, entire towehouse, shared room, other] and then encode.  
(2 marks)

In [15]:
sharedBath = ['Shared half-bath','Private half-bath','Half-bath','6 shared baths', '5.5 shared baths', '4.5 shared baths','4 shared baths', '3.5 shared baths', '3 shared baths', '2.5 shared baths','2 shared baths','1.5 shared baths','1 shared bath','7 shared baths']
oneBath = ['1 bath','1 private bath', '1.5 baths']
twoBath = ['2 baths', '2.5 baths']
threeBath = ['3 baths','3.5 baths']
manyBath = ['4 baths','4.5 baths','5 baths',  '5.5 baths','6 baths','6.5 baths', '11 baths', '19 baths']
for i in range(len(df)):
    if df['bathrooms'].loc[i] in sharedBath:
        df['bathrooms'].loc[i]= 'Shared bathrooms'
    if df['bathrooms'].loc[i] in oneBath:
        df['bathrooms'].loc[i]= 'One bathroom'
    if df['bathrooms'].loc[i] in twoBath:
        df['bathrooms'].loc[i]= 'Two bathrooms'
    if df['bathrooms'].loc[i] in threeBath:
        df['bathrooms'].loc[i]= 'Three bathrooms'
    if df['bathrooms'].loc[i] in manyBath:
        df['bathrooms'].loc[i]= 'Many bathrooms'
    if df['bathrooms'].loc[i] not in ['Shared bathrooms','One bathroom','Two bathrooms','Three bathrooms','Many bathrooms']:
        df['bathrooms'].loc[i]= 'Other'

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [16]:
for i in range(len(df)):
    if 'Room' in df['property_type'].loc[i]:
        df['property_type'].loc[i]= 'Entire room'
    if 'Private room' in df['property_type'].loc[i]:
        df['property_type'].loc[i]= 'Private room'
    if 'Shared room' in df['property_type'].loc[i]:
        df['property_type'].loc[i]= 'Shared room'  
entireTownhouse = ['Entire villa', 'Entire residential home','Entire guest suite','Entire guesthouse','Entire bungalow','Tiny house','Entire place','Entire vacation home','Dome house','Earth house','Casa particular']
entireRentalUnit = ['Entire serviced apartment', 'Entire loft', 'Entire rental unit', 'Entire condominium (condo)', 'Entire cottage']
for i in range(len(df)):
    if df['property_type'].loc[i] in entireTownhouse:
        df['property_type'].loc[i]= 'Entire townhouse'
    if df['property_type'].loc[i] in entireRentalUnit:
        df['property_type'].loc[i]= 'Entire rental unit'
        
notOther = ['Entire room', 'Private room','Shared room', 'Entire townhouse','Entire rental unit' ]
for i in range(len(df)):
    if df['property_type'].loc[i] not in notOther:
        df['property_type'].loc[i] = 'Other'

`(Task 2, Question 4 Text Here - insert more cells as required)`

**Task 2, Question 5**: Perform any other actions you think need to be done on the data before constructing predictive models, and clearly explain what you have done.   
(1 marks)

In [17]:
## Mapping the categorical value to numerical
type_map = {'Other':6, 'Entire townhouse':5, 'Entire rental unit':4, 'Entire room':3, 'Private room':2, 'Shared room': 1}
df['property_type_encoded']= df['property_type'].map(type_map)

bath_map = {'Shared bathrooms':0, 'One bathroom':1,'Two bathrooms':2,'Three bathrooms':3, 'Many bathrooms':4, 'Other':5 }
df['bathrooms']= df['bathrooms'].map(bath_map)

room_map = {'Shared room':1, 'Private room': 2, 'Hotel room':3, 'Entire home/apt':4}
df['room_type']= df['room_type'].map(room_map)

repTimeMap = {'within an hour':1, 'within a few hours':2, 'within a day':3, 'a few days or more':4 }
df['host_response_time']= df['host_response_time'].map(repTimeMap)

In [18]:
## Encoding True/False values to 1/0
truefalse_map = {'t':1, 'f':0}
df['host_is_superhost'] = df['host_is_superhost'].map(truefalse_map)
df['host_has_profile_pic'] = df['host_has_profile_pic'].map(truefalse_map)
df['host_identity_verified'] = df['host_identity_verified'].map(truefalse_map)
df['has_availability'] = df['has_availability'].map(truefalse_map)
df['instant_bookable'] = df['instant_bookable'].map(truefalse_map)

In [26]:
df.head()

,ID,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,amenities,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,price,host_email,host_phone,host_governmentId,host_jumio,host_reviews,kitchen,wifi,smoke_alarm,longterm_stay,essentials,property_type_encoded
0,0,Manly Harbour House,"Beautifully renovated, spacious and quiet, our...",Balgowlah Heights is one of the most prestigio...,Heidi,2009-11-20,"Sydney, New South Wales, Australia",I am a Canadian who has made Australia her hom...,2,1.0,0.69,1,Balgowlah,2.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",1,1,"Balgowlah, New South Wales, Australia",Manly,-33.80084,151.26378,Entire townhouse,4,6,3,3.0,3.0,"[""Hot water"", ""Coffee maker"", ""Heating"", ""Hair...",2,22,2.0,2.0,22.0,22.0,2.0,22.0,1,0,14,14,174.0,3,1,0,2016-01-02,2021-06-01,4.67,4.33,4.33,4.67,4.33,4.67,4.33,Exempt,0,2,2,0,0,0.04,470.0,1,1,1,1,1,1,1,1,0,1,5
1,1,Unique Designer Rooftop Apartment in City Loca...,Penthouse living at it best ... You will be st...,The location is really central and there is nu...,Morag,2009-12-03,"Sydney, New South Wales, Australia",I am originally Scottish but I have made Sydne...,1,1.0,1.00,0,Darlinghurst,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",1,1,"Darlinghurst, New South Wales, Australia",Sydney,-33.87964,151.21680,Private room,2,2,1,1.0,1.0,"[""Hot water"", ""Coffee maker"", ""Long term stays...",2,90,2.0,2.0,90.0,90.0,2.0,90.0,1,5,31,61,336.0,383,18,6,2012-02-23,2021-12-03,4.42,4.58,4.40,4.77,4.67,4.70,4.47,PID-STRA-24061-7,1,1,0,1,0,3.21,82.0,1,1,1,1,1,1,1,1,1,1,2
2,2,"Studio Yindi @ Mosman, Sydney","An open plan apartment, which opens onto a spa...","Mosman is a smart, middle to upper class subur...",John,2010-11-06,"Sydney, New South Wales, Australia",Faber est suae quisquae fortunae\r\n\r\nWe bec...,2,1.0,0.81,1,Mosman,1.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",1,1,"Mosman, New South Wales, Australia",Mosman,-33.81748,151.23484,Entire townhouse,4,4,1,1.0,1.0,"[""Hot water"", ""Coffee maker"", ""Long term stays...",2,90,2.0,2.0,90.0,90.0,2.0,90.0,1,1,9,33,217.0,297,15,4,2010-12-29,2021-11-30,4.55,4.66,4.23,4.87,4.90,4.73,4.68,PID-STRA-6093,0,1,1,0,0,2.23,150.0,1,1,1,1,1,1,1,1,1,1,5
3,3,"2br Eclectic Stylish Home, 2 mins to Bondi Beach","Two blocks to the beach, surf and coffee. Larg...",3 minutes to the beach and cafes. 5 minutes t...,Eilish,2010-11-25,"Bondi Beach, New South Wales, Australia","I'm a designer. I have lived in many cities, c...",3,1.0,1.00,1,Bondi Beach,1.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",1,1,"Bondi Beach, New South Wales, Australia",Waverley,-33.88905,151.27653,Entire rental unit,4,4,1,2.0,2.0,"[""Hot water"", ""Coffee maker"", ""Long term stays...",90,90,90.0,90.0,90.0,90.0,90.0,90.0,1,12,42,72,347.0,33,1,0,2011-04-09,2021-04-07,4.42,4.42,3.74,4.90,4.90,4.90,4.32,Unknown,0,1,1,0,0,0.25,245.0,1,1,1,1,1,1,1,1,1,1,4
4,4,A little bit of Sydney - Australia,"Hello Everyone,<br /><br />We have a quiet are...",Unknown,Bryan,2011-01-03,"Sydney, New South Wales, Australia",We are living in Sydney. We like to see Wine r...,1,1.0,0.89,1,Unknown,2.0,"['email', 'phone', 'reviews', 'jumio', 'offlin...",1,1,Unknown,NaN,-33.72966,151.05226,Private room,2,4,0,2.0,3.0,"[""Hot water"", ""Coffee maker"", ""Toaster"", ""Heat...",1,30,1.0,1.0,30.0,30.0,1.0,30.0,1,26,53,83,358.0,61,15,0,2011-06-21,2021-06-20,4.95,4.93,4.98,4.98,5.00,4.79,4.93,PID-STRA-9081,0,1,0,1,0,0.48,89.0,1,1,1,1,1,1,1,1,1,1,2

In [31]:
#Extract the training and test datasets as the original given datasets
df_training = df.loc[:6999]
df_testing = df.loc[7000:9999]

`(Task 2, Question 5 Text Here - insert more cells as required)`

**Task 2, Question 6**: Perform exploratory data analysis to measure the relationship between the features and the target and write up your findings. 
(2 marks)

In [20]:
## Task 2, Question 6 Code Here

`(Task 2, Question 6 Text Here - insert more cells as required)`

--- 
## Task 3: Fit and tune a forecasting model/Submit predictions/Report score and ranking

Make sure you **clearly explain each step** you do, both in text and on the recoded video.

1. Build a machine learning (ML) regression model taking into account the outcomes of Tasks 1 & 2
2. Fit the model and tune hyperparameters via cross-validation: make sure you comment and explain each step clearly
3. Create predictions using the test dataset and submit your predictions on Kaggle's competition page
4. Provide Kaggle ranking and **score** (screenshot your best submission) and comment
5. Make sure your Python code works, so that a marker that can replicate your all of your results and obtain the same MSE from Kaggle

- Hint: to perform well you will need to iterate Task 3, building and tuning various models in order to find the best one.

Total Marks: 11

In [48]:
#Task 3 code here
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import RANSACRegressor

#scores_v2 = cross_val_score(estimator=pipe_lr, X=X_train, y=y_train, cv=10, n_jobs=1)
y_train = df_training['price']
X_train = df_training.drop(columns = ['price','name','description','neighborhood_overview','host_name','host_since','host_location', 'host_about','host_verifications','host_neighbourhood', 'neighbourhood', 'neighbourhood_cleansed','first_review', 'last_review', 'property_type', 'amenities', 'license'])

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [50]:
scores_lr = cross_val_score(estimator=lr, X=X_train, y=y_train, cv=10, n_jobs=1)

# print(scores_v2)

print(f'CV accuracy scores\n {scores_lr.reshape(-1,1)}')
print(f'CV accuracy: {np.mean(scores_lr):.3f} +/- {np.std(scores_lr):.3f}')

CV accuracy scores
 [[0.56004475]
 [0.65365013]
 [0.60290741]
 [0.58269043]
 [0.4708505 ]
 [0.46891528]
 [0.45723437]
 [0.58774279]
 [0.38590666]
 [0.41025676]]
CV accuracy: 0.518 +/- 0.086

In [55]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
forest = RandomForestRegressor(n_estimators=1000, 
                               criterion='mse', 
                               random_state=1, 
                               n_jobs=-1)
forest.fit(X_train, y_train)

y_train_pred = forest.predict(X_train)


print(f'MSE train: {mean_squared_error(y_train, y_train_pred):.3f}')
print(f'R^2 train: {r2_score(y_train, y_train_pred):.3f}')

MSE train: 4984.992
R^2 train: 0.957

In [56]:
scores_fr = cross_val_score(estimator=forest, X=X_train, y=y_train, cv=10, n_jobs=1)

# print(scores_v2)

print(f'CV accuracy scores\n {scores_fr.reshape(-1,1)}')
print(f'CV accuracy: {np.mean(scores_fr):.3f} +/- {np.std(scores_fr):.3f}')

CV accuracy scores
 [[0.70278124]
 [0.67637078]
 [0.74321015]
 [0.72872566]
 [0.60652608]
 [0.66017666]
 [0.64042317]
 [0.69495913]
 [0.47946886]
 [0.54498088]]
CV accuracy: 0.648 +/- 0.079

In [61]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor(solver = 'lbfgs',random_state = 1, max_iter = 500)
mlp.fit(X_train, y_train)
y_train_pred = mlp.predict(X_train)
print(f'MSE train: {mean_squared_error(y_train, y_train_pred):.3f}')
print(f'R^2 train: {r2_score(y_train, y_train_pred):.3f}')

scores_mlp = cross_val_score(estimator=mlp, X=X_train, y=y_train, cv=10, n_jobs=1)

# print(scores_v2)

print(f'CV accuracy scores\n {scores_mlp.reshape(-1,1)}')
print(f'CV accuracy: {np.mean(scores_mlp):.3f} +/- {np.std(scores_mlp):.3f}')

MSE train: 249078.432
R^2 train: -1.170
CV accuracy scores
 [[-8.89307461e-01]
 [-1.59768809e+00]
 [-1.21004681e+00]
 [-5.05114295e-01]
 [-2.76971063e+06]
 [-7.79677832e-01]
 [-4.23761080e-01]
 [-5.31151486e-01]
 [-3.62853321e-01]
 [-9.68990159e-01]]
CV accuracy: -276971.790 +/- 830912.946

In [63]:
from sklearn.ensemble import BaggingRegressor
br = BaggingRegressor()
br.fit(X_train, y_train)
y_train_pred = br.predict(X_train)
print(f'MSE train: {mean_squared_error(y_train, y_train_pred):.3f}')
print(f'R^2 train: {r2_score(y_train, y_train_pred):.3f}')

MSE train: 7193.469
R^2 train: 0.937

In [42]:
df_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   ID                                            7000 non-null   int64
 1   name                                          7000 non-null   object
 2   description                                   7000 non-null   object
 3   neighborhood_overview                         7000 non-null   object
 4   host_name                                     7000 non-null   object
 5   host_since                                    7000 non-null   object
 6   host_location                                 7000 non-null   object
 7   host_about                                    7000 non-null   object
 8   host_response_time                            7000 non-null   int64
 9   host_response_rate                            7000 non-null   float64
 10  host_acceptance_rate                          7000 non-null   float64
 11  host_is_superhost                             7000 non-null   int64
 12  host_neighbourhood                            7000 non-null   object
 13  host_listings_count                           7000 non-null   float64
 14  host_verifications                            7000 non-null   object
 15  host_has_profile_pic                          7000 non-null   int64
 16  host_identity_verified                        7000 non-null   int64
 17  neighbourhood                                 7000 non-null   object
 18  neighbourhood_cleansed                        6892 non-null   object
 19  latitude                                      7000 non-null   float64
 20  longitude                                     7000 non-null   float64
 21  property_type                                 7000 non-null   object
 22  room_type                                     7000 non-null   int64
 23  accommodates                                  7000 non-null   int64
 24  bathrooms                                     7000 non-null   int64
 25  bedrooms                                      7000 non-null   float64
 26  beds                                          7000 non-null   float64
 27  amenities                                     7000 non-null   object
 28  minimum_nights                                7000 non-null   int64
 29  maximum_nights                                7000 non-null   int64
 30  minimum_minimum_nights                        7000 non-null   float64
 31  maximum_minimum_nights                        7000 non-null   float64
 32  minimum_maximum_nights                        7000 non-null   float64
 33  maximum_maximum_nights                        7000 non-null   float64
 34  minimum_nights_avg_ntm                        7000 non-null   float64
 35  maximum_nights_avg_ntm                        7000 non-null   float64
 36  has_availability                              7000 non-null   int64
 37  availability_30                               7000 non-null   int64
 38  availability_60                               7000 non-null   int64
 39  availability_90                               7000 non-null   int64
 40  availability_365                              7000 non-null   float64
 41  number_of_reviews                             7000 non-null   int64
 42  number_of_reviews_ltm                         7000 non-null   int64
 43  number_of_reviews_l30d                        7000 non-null   int64
 44  first_review                                  7000 non-null   datetime64[ns]
 45  last_review                                   7000 non-null   datetime64[ns]
 46  review_scores_rating                          7000 non-null   float64
 47  review_scores_accuracy                        7000 non-null   float64
 48  review_scores_cleanliness                     7000 non-null   float64
 49  review_scores_checkin                         7000 non-null   float64
 50  review_scores_communication                   7000 non-null   float64
 51  review_scores_location                        7000 non-null   float64
 52  review_scores_value                           7000 non-null   float64
 53  license                                       7000 non-null   object
 54  instant_bookable                              7000 non-null   int64
 55  calculated_host_listings_count                7000 non-null   int64
 56  calculated_host_listings_count_entire_homes   7000 non-null   int64
 57  calculated_host_listings_count_private_rooms  7000 non-null   int64
 58  calculated_host_listings_count_shared_rooms   7000 non-null   int64
 59  reviews_per_month                             7000 non-null   float64
 60  price                                         7000 non-null   float64
 61  host_email                                    7000 non-null   int64
 62  host_phone                                    7000 non-null   int64
 63  host_governmentId                             7000 non-null   int64
 64  host_jumio                                    7000 non-null   int64
 65  host_reviews                                  7000 non-null   int64
 66  kitchen                                       7000 non-null   int64
 67  wifi                                          7000 non-null   int64
 68  smoke_alarm                                   7000 non-null   int64
 69  longterm_stay                                 7000 non-null   int64
 70  essentials                                    7000 non-null   int64
 71  property_type_encoded                         7000 non-null   int64
dtypes: datetime64[ns](2), float64(23), int64(33), object(14)
memory usage: 3.8+ MB

`(Task 3 - insert more cells as required)`